[meta]
name = "PlayerState"
author = "Thommie"
category = "Race"
siteid = 191
version = "1.3.1"

[script]
dependencies = [ "MLHook", "MLFeedRaceData" ]
exports = [ "Exports.as" ]
shared_exports = [ "AR_Data.as" ]
export_dependencies = [ "MLHook", "MLFeedRaceData" ]
